#默认配置
title: 瓦力博客  
description: 成长不只有痛苦，也有乐趣   #描述
show_downloads: true   
exclude: ['filestruct.txt']  #排除某个文件
include: [] #强制包含某些文件
keep_files: []  #当生成站点时，保留选择的文件
Encoding: utf-8   #编码

#插件分页
gems: [jekyll-paginate,pager,pagination]

paginate: 7
paginate_path: "blog/page:num"  #首页分页
paginatepath: ["aaaa/page/:num","bbbb/page/:num","cccc/page/:num","jekyll/page/:num"]

compress_html:    #html配置
  clippings: all
  comments: all
  endings: all
  profile: true
  startings: [head, body]
sass:      #sass配置
    style:     nested    #压缩
    

#服务器配置
host: 127.0.0.1
port: 4002
baseurl: "/"    #网站的根路径 
url: "http://ozk28a7ln.bkt.clouddn.com" #change this to the base hostname & protocol for your site
publicPath: "" #'http://ozk28a7ln.bkt.clouddn.com' #公共路径

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

#个人信息
author: "waliDream"
image: /thumbnail-jumbo.png
twitter:
  username: waliDream
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:










